TEAMS_ALIVE_MASK = {
    "Memphis": 0,
    "New Mexico": 0,
    "Purdue": 0,
    "Lipscomb": 0,
    "Texas": 0,
    "UC San Diego": 0,
    "Creighton": 0,
    "Marquette": 0,
    "SIUE": 0,
    "Omaha": 0,
    "Yale": 0,
    "Wisconsin": 0,
    "Drake": 0,
    "Norfolk St.": 0,
    "Duke": 1,
    "Colo. St.": 0,
    "Auburn": 1,
    "Alabama": 0,
    "Miss. St.": 0,
    "Bryant": 0,
    "St. John's": 0,
    "Texas Tech": 0,
    "Tennessee": 0,
    "Florida": 1,
    "Kansas": 0,
    "Xavier": 0,
    "Iowa St.": 0,
    "Gonzaga": 0,
    "North Carolina": 0,
    "American": 0,
    "Vanderbilt": 0,
    "Utah St.": 0,
    "Oklahoma": 0,
    "Michigan": 0,
    "Arizona": 0,
    "Clemson": 0,
    "Louisville": 0,
    "Kentucky": 0,
    "Maryland": 0,
    "BYU": 0,
    "Baylor": 0,
    "Texas A&M": 0,
    "Arkansas": 0,
    "Georgia": 0,
    "Houston": 1,
    "VCU": 0,
    "Alabama St.": 0,
    "Robert Morris": 0,
    "Illinois": 0,
    "Ole Miss": 0,
    "Grand Canyon": 0,
    "UConn": 0,
    "UNCW": 0,
    "High Point": 0,
    "Saint Mary's": 0,
    "Troy": 0,
    "Wofford": 0,
    "Oregon": 0,
    "Missouri": 0,
    "Akron": 0,
    "UCLA": 0,
    "Liberty": 0,
    "Montana": 0,
    "San Diego St.": 0,
    "St. Fran.-Pa.": 0,
    "Mt St Mary's": 0,
    "McNeese": 0,
    "Mich. St.": 0
}

ESPN_TO_PP_MAP = {
    "Alabama State Hornets": "Alabama St.",
    "Auburn Tigers": "Auburn",
    "Creighton Bluejays": "Creighton",
    "Louisville Cardinals": "Louisville",
    "UC San Diego Tritons": "UC San Diego",
    "Michigan Wolverines": "Michigan",
    "Yale Bulldogs": "Yale",
    "Texas A&M Aggies": "Texas A&M",
    "North Carolina Tar Heels": "North Carolina",
    "Ole Miss Rebels": "Ole Miss",
    "Lipscomb Bisons": "Lipscomb",
    "Iowa State Cyclones": "Iowa St.",
    "New Mexico Lobos": "New Mexico",
    "Marquette Golden Eagles": "Marquette",
    "Bryant Bulldogs": "Bryant",
    "Michigan State Spartans": "Mich. St.",
    "Baylor Bears": "Baylor",
    "Duke Blue Devils": "Duke",
    "BYU Cougars": "BYU",
    "Wisconsin Badgers": "Wisconsin",
    "Saint Mary's Gaels": "Saint Mary's",
    "Alabama Crimson Tide": "Alabama",
    "Mount St. Mary's Mountaineers": "Mt St Mary's",
    "Mississippi State Bulldogs": "Miss. St.",
    "Liberty Flames": "Liberty",
    "Oregon Ducks": "Oregon",
    "Akron Zips": "Akron",
    "Arizona Wildcats": "Arizona",
    "VCU Rams": "VCU",
    "Montana Grizzlies": "Montana",
    "Vanderbilt Commodores": "Vanderbilt",
    "Robert Morris Colonials": "Robert Morris",
    "Norfolk State Spartans": "Norfolk St.",
    "Florida Gators": "Florida",
    "Oklahoma Sooners": "Oklahoma",
    "UConn Huskies": "UConn",
    "Colorado State Rams": "Colo. St.",
    "Memphis Tigers": "Memphis",
    "Grand Canyon Lopes": "Grand Canyon",
    "Maryland Terrapins": "Maryland",
    "Drake Bulldogs": "Drake",
    "Missouri Tigers": "Missouri",
    "UNC Wilmington Seahawks": "UNCW",
    "Texas Tech Red Raiders": "Texas Tech",
    "Arkansas Razorbacks": "Arkansas",
    "Kansas Jayhawks": "Kansas",
    "Omaha Mavericks": "Omaha",
    "St. John's Red Storm": "St. John's",
    "Gonzaga Bulldogs": "Gonzaga",
    "Houston Cougars": "Houston",
    "McNeese Cowboys": "McNeese",
    "Purdue Boilermakers": "Purdue",
    "UCLA Bruins": "UCLA",
    "Tennessee Volunteers": "Tennessee",
    "SIU Edwardsville Cougars": "SIUE",
    "Georgia Bulldogs": "Georgia",
    "Clemson Tigers": "Clemson",
    "High Point Panthers": "High Point",
    "Xavier Musketeers": "Xavier",
    "Illinois Fighting Illini": "Illinois",
    "Troy Trojans": "Troy",
    "Kentucky Wildcats": "Kentucky",
    "Utah State Aggies": "Utah St.",
    "Wofford Terriers": "Wofford",
    "San Diego State Aztecs": "San Diego St.",
    "St. Francis (PA) Red Flash": "St. Fran.-Pa.",
    "American University Eagles": "American",
    "Texas Longhorns": "Texas"
}

PP_TO_SILVER_MAP = {
    "Auburn": "Auburn",
    "Duke": "Duke",
    "Houston": "Houston",
    "Florida": "Florida",
    "St. John's": "St. John's",
    "Mich. St.": "Michigan St.",
    "Tennessee": "Tennessee",
    "Alabama": "Alabama",
    "Wisconsin": "Wisconsin",
    "Texas Tech": "Texas Tech",
    "Arizona": "Arizona",
    "Iowa St.": "Iowa St.",
    "Kentucky": "Kentucky",
    "Maryland": "Maryland",
    "Clemson": "Clemson",
    "Texas A&M": "Texas A&M",
    "Oregon": "Oregon",
    "Kansas": "Kansas",
    "Purdue": "Purdue",
    "Gonzaga": "Gonzaga",
    "Saint Mary's": "Saint Mary's (CA)",
    "UConn": "UConn",
    "UCLA": "UCLA",
    "Louisville": "Louisville",
    "Marquette": "Marquette",
    "BYU": "BYU",
    "Illinois": "Illinois",
    "Michigan": "Michigan",
    "Missouri": "Missouri",
    "Ole Miss": "Ole Miss",
    "Baylor": "Baylor",
    "Colo. St.": "Colorado St.",
    "Memphis": "Memphis",
    "Miss. St.": "Mississippi St.",
    "Drake": "Drake",
    "UC San Diego": "UC San Diego",
    "VCU": "VCU",
    "New Mexico": "New Mexico",
    "Creighton": "Creighton",
    "Utah St.": "Utah St.",
    "North Carolina": "North Carolina",
    "Oklahoma": "Oklahoma",
    "Vanderbilt": "Vanderbilt",
    "Georgia": "Georgia",
    "High Point": "High Point",
    "Arkansas": "Arkansas",
    "Xavier": "Xavier",
    "Liberty": "Liberty",
    "Yale": "Yale",
    "McNeese": "McNeese",
    "Grand Canyon": "Grand Canyon",
    "Troy": "Troy",
    "Texas": "Texas",
    "San Diego St.": "San Diego St.",
    "Lipscomb": "Lipscomb",
    "Akron": "Akron",
    "UNCW": "UNC Wilmington",
    "Montana": "Montana",
    "Robert Morris": "Robert Morris",
    "Wofford": "Wofford",
    "Bryant": "Bryant",
    "Omaha": "Omaha",
    "Norfolk St.": "Norfolk St.",
    "SIUE": "SIU Edwardsville",
    "Mt St Mary's": "Mount St. Mary's (MD)",
    "Alabama St.": "Alabama St.",
    "American": "American",
    "St. Fran.-Pa.": "Saint Francis (PA)"
}


sr_to_kenpom = {
    'Brigham Young': 'BYU',
    'Saint Mary\'s (CA)': 'Saint Mary\'s',
    'St. John\'s (NY)': 'St. John\'s',
    'Pittsburgh': 'Pittsburgh',
    'Mississippi State': 'Mississippi St.',
    'Central Florida': 'UCF',
    'Virginia Commonwealth': 'VCU',
    'Southern California': 'USC',
    'Ole Miss': 'Mississippi',
    'Massachusetts': 'UMass',
    'Miami (FL)': 'Miami FL',
    'Nevada-Las Vegas': 'UNLV',
    'North Carolina State': 'N.C. State',
    'Louisiana State': 'LSU',
    'Connecticut': 'Connecticut',
    'North Carolina': 'North Carolina',
    'Pittsburgh': 'Pittsburgh',
    'St. John\'s (NY)': 'St. John\'s',
    'Louisiana State': 'LSU',
    'Central Florida': 'UCF',
    'Texas A&M-Corpus Christi': 'Texas A&M Corpus Chris',
    'Purdue Fort Wayne': 'Purdue Fort Wayne',
    'Loyola (IL)': 'Loyola Chicago',
    'College of Charleston': 'Charleston',
    'Loyola (IL)': 'Loyola Chicago',
    'Saint Joseph\'s': 'Saint Joseph\'s',
    'Saint Francis (PA)': 'Saint Francis',
    'Arkansas-Pine Bluff': 'Arkansas Pine Bluff',
    'SIU Edwardsville': 'SIU Edwardsville',
    'Maryland-Baltimore County': 'UMBC',
    'Maryland-Eastern Shore': 'Maryland Eastern Shore',
    'Massachusetts-Lowell': 'UMass Lowell',
    'Charleston Southern': 'Charleston Southern',
    'East Tennessee State': 'East Tennessee St.',
    'Florida International': 'FIU',
    'Loyola (IL)': 'Loyola Chicago',
    'Albany (NY)': 'Albany',
    'College of Charleston': 'Charleston',
    'Detroit Mercy': 'Detroit Mercy',
    'LIU': 'LIU',
    'North Carolina State': 'N.C. State',
    'Southeast Missouri State': 'Southeast Missouri St.',
    'Louisiana-Monroe': 'Louisiana Monroe',
    'Nicholls State': 'Nicholls St.',
    'Middle Tennessee': 'Middle Tennessee',
    'UMass Lowell': 'UMass Lowell',
    'UNC Asheville': 'UNC Asheville',
    'UNC Greensboro': 'UNC Greensboro',
    'UNC Wilmington': 'UNC Wilmington',
    'Texas-Rio Grande Valley': 'UT Rio Grande Valley',
    'Western Carolina': 'Western Carolina',
    'Northern Illinois': 'Northern Illinois',
    'Southern Illinois': 'Southern Illinois',
    'Fairleigh Dickinson': 'Fairleigh Dickinson',
    'Alcorn State': 'Alcorn St.',
    'Cal State Bakersfield': 'Cal St. Bakersfield',
    'Cal State Fullerton': 'Cal St. Fullerton',
    'Cal State Northridge': 'Cal St. Northridge',
    'Prairie View': 'Prairie View A&M',
    'Southern Methodist': 'SMU',
    'Southern Mississippi': 'Southern Miss',
    'East Tennessee State': 'East Tennessee St.',
    'Eastern Illinois': 'Eastern Illinois',
    'Eastern Kentucky': 'Eastern Kentucky',
    'Eastern Michigan': 'Eastern Michigan',
    'Eastern Washington': 'Eastern Washington',
    'Illinois-Chicago': 'Illinois Chicago',
    'Kansas City': 'UMKC',
    'Louisiana-Monroe': 'Louisiana Monroe',
    'Maryland-Eastern Shore': 'Maryland Eastern Shore',
    'Tennessee-Martin': 'Tennessee Martin',
    'Texas Southern': 'Texas Southern',
    'North Dakota State': 'North Dakota St.',
    'Southeast Missouri State': 'Southeast Missouri St.',
    'Virginia Commonwealth': 'VCU',
    'UConn': 'Connecticut',
    'San Diego State': 'San Diego St.',
    'Morehead State': 'Morehead St.',
    'Washington State': 'Washington St.',
    'Iowa State': 'Iowa St.',
    'South Dakota State': 'South Dakota St.',
    'UNC': 'North Carolina',
    'Michigan State': 'Michigan St.',
    'Long Beach State': 'Long Beach St.',
    'NC State': 'N.C. State',
    'Grambling': 'Grambling St.',
    'Utah State': 'Utah St.',
    'McNeese State': 'McNeese St.',
    'Colorado State': 'Colorado St.',
    'St. Peter\'s': 'Saint Peter\'s',
    'St. John\'s (NY)': 'St. John\'s',
    'Saint Mary\'s': 'Saint Mary\'s (CA)',
    'Mississippi State': 'Mississippi St.',
    'Norfolk State': 'Norfolk St.',
    'Colorado State': 'Colorado St.',
    'Alabama State': 'Alabama St.',
    'UC-San Diego': 'UC San Diego',
    'UNC': 'North Carolina',
    'Iowa State': 'Iowa St.',
    'Michigan State': 'Michigan St.',
    'SIU-Edwardsville': 'SIU Edwardsville',
    'McNeese State': 'McNeese St.',
    'Utah State': 'Utah St.',
    
}

sr_to_silver = {
    'St. John\'s (NY)': 'St. John\'s',
    'Saint Mary\'s': 'Saint Mary\'s (CA)',
    'Mississippi State': 'Mississippi St.',
    'Norfolk State': 'Norfolk St.',
    'Colorado State': 'Colorado St.',
    'Alabama State': 'Alabama St.',
    'UC-San Diego': 'UC San Diego',
    'UNC': 'North Carolina',
    'Iowa State': 'Iowa St.',
    'Michigan State': 'Michigan St.',
    'SIU-Edwardsville': 'SIU Edwardsville',
    'McNeese State': 'McNeese',
    'Utah State': 'Utah St.',
}